## Web Scraping
- web scraping is a tech

### Required libraries to collect the data
1. requests
2. BeautifulSoup

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

1. 200 --> success
2. 400-500 --> client side error
3. 500+ -->server side error
4. 404 --> page not found

In [17]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,/;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    # 'Accept-Encoding': 'gzip, deflate, br',
    'DNT': '1',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'none',
    'Sec-Fetch-User': '?1',
}

In [21]:
url = "https://coinmarketcap.com/"
page = requests.get(url, headers=headers)
page

In [23]:
page.text

'<!DOCTYPE html><html lang="en" dir="ltr"><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"/><meta property="og:url" content="https://coinmarketcap.com/"/><link rel="canonical" href="https://coinmarketcap.com/"/><link rel="alternate" hrefLang="ar" href="https://coinmarketcap.com/ar/"/><link rel="alternate" hrefLang="bg" href="https://coinmarketcap.com/bg/"/><link rel="alternate" hrefLang="cs" href="https://coinmarketcap.com/cs/"/><link rel="alternate" hrefLang="da" href="https://coinmarketcap.com/da/"/><link rel="alternate" hrefLang="de" href="https://coinmarketcap.com/de/"/><link rel="alternate" hrefLang="el" href="https://coinmarketcap.com/el/"/><link rel="alternate" hrefLang="en" href="https://coinmarketcap.com/"/><link rel="alternate" hrefLang="es" href="https://coinmarketcap.com/es/"/><link rel="alternate" hrefLang="fi" href="https://coinmarketcap.com/fi/"/><link rel="alternate" hrefLang="fr" href="https://coinmarketcap.com/fr/"/><link rel="alternate" hrefLang="hi" href="https://coinmarketcap.com/hi/"/><link rel="alternate" hrefLang="hu" href="https://coinmarketcap.com/hu/"/><link rel="alternate" hrefLang="id" href="https://coinmarketcap.com/id/"/><link rel="alternate" hrefLang="it" href="https://coinmarketcap.com/it/"/><link rel="alternate" hrefLang="ja" href="https://coinmarketcap.com/ja/"/><link rel="alternate" hrefLang="ko" href="https://coinmarketcap.com/ko/"/><link rel="alternate" hrefLang="nl" href="https://coinmarketcap.com/nl/"/><link rel="alternate" hrefLang="no" href="https://coinmarketcap.com/no/"/><link rel="alternate" hrefLang="pl" href="https://coinmarketcap.com/pl/"/><link rel="alternate" hrefLang="pt-br" href="https://coinmarketcap.com/pt-br/"/><link rel="alternate" hrefLang="ro" href="https://coinmarketcap.com/ro/"/><link rel="alternate" hrefLang="ru" href="https://coinmarketcap.com/ru/"/><link rel="alternate" hrefLang="sk" href="https://coinmarketcap.com/sk/"/><link rel="alternate" hrefLang="sv" href="https://coinmarketcap.com/sv/"/><link rel="alternate" hrefLang="th" href="https://coinmarketcap.com/th/"/><link rel="alternate" hrefLang="tr" href="https://coinmarketcap.com/tr/"/><link rel="alternate" hrefLang="uk" href="https://coinmarketcap.com/uk/"/><link rel="alternate" hrefLang="ur" href="https://coinmarketcap.com/ur/"/><link rel="alternate" hrefLang="vi" href="https://coinmarketcap.com/vi/"/><link rel="alternate" hrefLang="zh-tw" href="https://coinmarketcap.com/zh-tw/"/><link rel="alternate" hrefLang="zh" href="https://coinmarketcap.com/zh/"/><link rel="manifest" href="/manifest.json"/><title>Cryptocurrency Prices, Charts And Market Capitalizations | CoinMarketCap</title><meta property="og:title" content="Cryptocurrency Prices, Charts And Market Capitalizations | CoinMarketCap"/><meta name="description" content="Top cryptocurrency prices and charts, listed by market capitalization. Free access to current and historic data for Bitcoin and thousands of altcoins."/><meta property="og:description" content="Top cryptocurrency prices and charts, listed by market capitalization. Free access to current and historic data for Bitcoin and thousands of altcoins."/><script type="application/ld+json">{"@context":"http://schema.org","@type":"Organization","name":"CoinMarketCap","url":"https://coinmarketcap.com","logo":"https://coinmarketcap.com/apple-touch-icon.png","sameAs":["https://www.facebook.com/CoinMarketCap/","https://twitter.com/coinmarketcap"]}</script><script type="application/ld+json">{"@context":"http://schema.org","@type":"Table","about":"Cryptocurrency Prices Today"}</script><meta name="next-head-count" content="43"/><script>if(top!==self){location.href="about:blank";}</script><script>\n              const blocklist = [\'/currencies/ethereum/\',\'/currencies/xrp/\',\'/currencies/victoria-vr/\',\'/currencies/aioz-network/\',\'/currencies/smartofgiving/\',\'/currencies/xrp-army/\'];\n              if(navigator.userAgent.includes("Googlebot") && blocklist.some(path => location.pathname.includes(path))) {\n                const meta = document.createElement("meta");\n                meta.setAttribute("http-equiv", "Content-Security-Policy");\n                meta.setAttribute("content", "default-src \'none\'; base-uri \'none\'");\n                document.head.appendChild(meta);\n              }\n              </script><style data-static="ui-tokens">:root{--c-font-size-50:11px;--c-font-size-75:12px;--c-font-size-100:14px;--c-font-size-200:16px;--c-font-size-300:18px;--c-font-size-400:18px;--c-font-size-600:20px;--c-font-size-800:25px;--c-font-size-1000:32px;--c-font-weight-300:300;--c-font-weight-400:400;--c-font-weight-500:500;--c-font-weight-600:600;--c-font-weight-700:700;--c-font-weight-900:900;--c-line-height-heading:130%;--c-line-height-body:150%;--c-color-gray-100:#F8FAFD;--c-color-gray-200:#EFF2F5;--c-color-gray-300:#CFD6E4;--c-color-gray-400:#A6B0C3;--c-color-gray-500:#808A9D;--c-color-gray-600:#616E85;--c-color-blue-100:#F0F6FF;--c-color-blue-200:#DDE4FD;--c-color-blue-300:#ACBDFB;--c-color-blue-400:#6188FF;--c-color-blue-500:#3861FB;--c-color-blue-600:#2444D4;--c-color-blue-700:#0728A1;--c-color-blue-800:#1E274F;--c-color-green-100:#DEFBF0;--c-color-green-200:#C3F8E4;--c-color-green-300:#8CF2CC;--c-color-green-400:#67E4B5;--c-color-green-500:#16C784;--c-color-green-600:#119C68;--c-color-green-700:#0D734C;--c-color-green-800:#173C37;--c-color-beige-100:#FDF4EA;--c-color-beige-200:#FCEDDE;--c-color-beige-300:#FBE0C6;--c-color-beige-400:#F9D3AF;--c-color-beige-500:#F5B97F;--c-color-beige-600:#EE8B2A;--c-color-beige-700:#BD650F;--c-color-beige-800:#433936;--c-color-orange-100:#FFE9E5;--c-color-orange-200:#FFCFC7;--c-color-orange-300:#FFAD9E;--c-color-orange-400:#FF9B8A;--c-color-orange-500:#FF775F;--c-color-orange-600:#FF3C1A;--c-color-orange-700:#D11F00;--c-color-orange-800:#8A1500;--c-color-red-100:#FCE6E8;--c-color-red-200:#F8BABD;--c-color-red-300:#F8BABD;--c-color-red-400:#EE626A;--c-color-red-500:#EA3943;--c-color-red-600:#CB1620;--c-color-red-700:#981018;--c-color-red-800:#411F2A;--c-color-teal-100:#E8FAFD;--c-color-teal-200:#B9EFF9;--c-color-teal-300:#7CE1F3;--c-color-teal-400:#3BD1ED;--c-color-teal-500:#13B2CF;--c-color-teal-600:#0F91A8;--c-color-teal-700:#0C7487;--c-color-teal-800:#084854;--c-color-purple-100:#F6F0FF;--c-color-purple-200:#E7D7FE;--c-color-purple-300:#C8A5FE;--c-color-purple-400:#A972FD;--c-color-purple-500:#8A3FFC;--c-color-purple-600:#6312DE;--c-color-purple-700:#4103A1;--c-color-purple-800:#25015A;--c-color-blue-black:var(--c-color-blue-700);--c-color-blue-dark:var(--c-color-blue-600);--c-color-blue-original:var(--c-color-blue-500);--c-color-blue-light:var(--c-color-blue-400);--c-color-green-black:var(--c-color-green-700);--c-color-green-dark:var(--c-color-green-600);--c-color-green-original:var(--c-color-green-500);--c-color-green-light:var(--c-color-green-400);--c-color-beige-black:var(--c-color-beige-700);--c-color-beige-dark:var(--c-color-beige-600);--c-color-beige-original:var(--c-color-beige-500);--c-color-beige-light:var(--c-color-beige-400);--c-color-orange-black:var(--c-color-orange-700);--c-color-orange-dark:var(--c-color-orange-600);--c-color-orange-original:var(--c-color-orange-500);--c-color-orange-light:var(--c-color-orange-400);--c-color-teal-black:var(--c-color-teal-700);--c-color-teal-dark:var(--c-color-teal-600);--c-color-teal-original:var(--c-color-teal-500);--c-color-teal-light:var(--c-color-teal-400);--c-color-purple-black:var(--c-color-purple-700);--c-color-purple-dark:var(--c-color-purple-600);--c-color-purple-original:var(--c-color-purple-500);--c-color-purple-light:var(--c-color-purple-400);--c-color-blue:#3861FB;--c-color-background-1:#FCFDFE;--c-color-background-2:#FFFFFF;--c-color-surface-1:#FFFFFF;--c-color-surface-2:#F8FAFD;--c-color-text-primary:#0D1421;--c-color-text-secondary:#616E85;--c-color-text-caption:#A6B0C3;--c-color-text-hyperlink:#3861FB;--c-color-negative:#EA3943;--c-color-negative-bg:var(--c-color-red-100);--c-color-positive:#16C784;--c-color-positive-bg:var(--c-color-green-100);--c-color-reminder:#F5B97F;--c-color-reminder-bg:var(--c-color-beige-100);--c-color-official:#3861FB;--c-color-official-bg:var(--c-color-blue-100);--c-color-no-access:#858CA2;--c-color-no-access-bg:var(--c-color-gray-200);--c-color-azure:#486DF7;--c-color-green:var(--c-color-green-500);--c-color-beige:var(--c-color-beige-500);--c-color-orange:var(--c-color-orange-500);--c-color-teal:#23DCF5;--c-color-purple:var(--c-color-purple-500);--c-color-navy:var(--c-color-blue-600);--c-color-overlay-bg:rgba(88, 102, 126, 0.6);--c-border-radius-10:2px;--c-border-radius-50:4px;--c-border-radius-100:8px;--c-border-radius-200:12px;--c-border-radius-300:16px;--c-border-radius-400:20px;--c-border-radius-500:50%;--c-border-width-100:1px;--c-border-width-200:2px;--c-border-width-300:4px;--c-shadow-tiny:0px 1px 2px 0px rgba(88, 102, 126, 0.12), 0px 4px 24px 0px rgba(88, 102, 126, 0.08);--c-shadow-overlay:0px 8px 32px 0px rgba(128, 138, 157, 0.24), 0px 1px 2px 0px rgba(128, 138, 157, 0.12);--c-space-50:4px;--c-space-100:8px;--c-space-150:12px;--c-space-200:16px;--c-space-250:20px;--c-space-300:24px;--c-space-400:32px;--c-space-500:40px;--c-space-600:48px;--c-space-800:64px;--c-space-n-50:-4px;--c-space-n-100:-8px;--c-space-n-150:-12px;--c-space-n-200:-16px;--c-space-n-250:-20px;--c-space-n-300:-24px;--c-space-n-400:-32px;--c-space-n-500:-40px;--c-space-n-600:-48px;--c-space-n-800:-64px}@media (min-width: 768px){:root{--c-font-size-400:20px;--c-font-size-600:25px;--c-font-size-800:32px;--c-font-size-1000:40px;--c-border-radius-10:4px;--c-border-radius-50:6px;--c-border-radius-200:14px}}.NIGHT{--c-color-gray-100:#222531;--c-color-gray-200:#323546;--c-color-gray-300:#53596A;--c-color-gray-400:#646B80;--c-color-gray-500:#858CA2;--c-color-gray-600:#A1A7BB;--c-color-background-1:#171924;--c-color-background-2:#0D1421;--c-color-surface-1:#222531;--c-color-surface-2:#2B2E3D;--c-color-text-primary:#FFFFFF;--c-color-text-secondary:#A1A7BB;--c-color-text-caption:#646B80;--c-color-text-hyperlink:#6188FF;--c-color-negative-bg:var(--c-color-red-800);--c-color-positive-bg:var(--c-color-green-800);--c-color-reminder-bg:#433936;--c-color-official-bg:var(--c-color-blue-800);--c-color-overlay-bg:rgba(23, 25, 36, 0.6);--c-shadow-tiny:0px 1px 2px 0px rgba(13, 20, 33, 0.24), 0px 4px 24px 0px rgba(13, 20, 33, 0.12);;--c-shadow-overlay:0px 8px 32px 0px #0D1421, 0px 1px 2px 0px #0D1421}</style><link rel="preload" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Regular-new.woff2" as="font" type="font/woff2" crossorigin="anonymous"/><link href="https://s2.coinmarketcap.com/static/cloud/styles/ui_v072v1.css" rel="stylesheet"/><link rel="preload" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Medium-new.woff2" as="font" type="font/woff2" crossorigin="anonymous"/><link rel="preload" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-SemiBold-new.woff2" as="font" type="font/woff2" crossorigin="anonymous"/><link rel="preload" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Bold-new.woff2" as="font" type="font/woff2" crossorigin="anonymous"/><link rel="preload" href="https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.woff" as="font" type="font/woff" crossorigin="anonymous"/><style>@font-face{font-family:\'Inter\';font-style:normal;font-weight:400;src:url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Regular-new.woff2\') format(\'woff2\'),url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Regular-new.woff\') format(\'woff\');font-display:swap;}@font-face{font-family:\'Inter\';font-style:normal;font-weight:500;src:url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Medium-new.woff2\') format(\'woff2\'),url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Medium-new.woff\') format(\'woff\');font-display:swap;}@font-face{font-family:\'Inter\';font-style:normal;font-weight:600;src:url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-SemiBold-new.woff2\') format(\'woff2\'),url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-SemiBold-new.woff\') format(\'woff\');font-display:swap;}@font-face{font-family:\'Inter\';font-style:normal;font-weight:700;src:url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Bold-new.woff2\') format(\'woff2\'),url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Bold-new.woff\') format(\'woff\');font-display:swap;}@font-face{font-family:\'Inter\';font-style:normal;font-weight:900;src:url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Black-new.woff2\') format(\'woff2\'),url(\'https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Black-new.woff\') format(\'woff\');font-display:swap;}@font-face{font-family:\'CMC V2\';src:url(\'https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.woff\') format(\'woff\'),url(\'https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.ttf\') format(\'truetype\'),url(\'https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.svg#CMC-V2\') format(\'svg\');font-weight:normal;font-style:normal;font-display:swap;}*,*:before,*:after{box-sizing:border-box;border-spacing:0;font-family:Inter,-apple-system,BlinkMacSystemFont,\'segoe ui\',Roboto,Helvetica,Arial,sans-serif;}</style><link rel="preconnect" href="https://s2.coinmarketcap.com" crossorigin="anonymous"/><link rel="preconnect" href="https://s3.coinmarketcap.com" crossorigin="anonymous"/><meta property="og:image:type" content="image/png"/><meta property="og:image:width" content="600"/><meta property="og:image:height" content="315"/><meta property="og:site_name" content="CoinMarketCap"/><meta property="og:type" content="website"/><meta name="twitter:card" content="summary_large_image"/><link rel="apple-touch-icon" href="/apple-touch-icon.png"/><link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/><link rel="preload" href="https://cdn.fuseplatform.net/publift/tags/2/3570/fuse.js" as="script"/><meta property="og:image" content="https://s2.coinmarketcap.com/static/cloud/img/splash_600x315_1.png?_=6da0a97"/><meta name="google-site-verification" content="EDc1reqlQ-zAgeRrrgAxRXNK-Zs9JgpE9a0wdaoSO9A"/><script>const __cookieBannerInitialScriptsDemoCode=()=>{let e=["ar","bg","cs","da","de","el","en","es","fi","fr","hi","hu","id","it","ja","ko","nl","no","pl","pt-br","ro","ru","sk","sv","th","tr","uk","ur","vi","zh-tw","zh"];function t(t){let n=e.join("|"),r=RegExp(`^/(${n})/?`);return t.replace(r,"/")}let n=!("cn-test.coinmarketcap.com"===location.host||"coinmarketcap.com"===location.host);function r(){let e=new Date(JSON.parse(localStorage.getItem("appBannerAppear")||"{}").value||0).getTime();return new Date().getTime()-e<(n?6e4:864e6)}function a(e){let t=e,n=t.includes("utm_source=coinmarketcap")||t.includes("app=");if(n)try{localStorage.setItem("cmc_flag_in_app","true")}catch(r){}return n}function i(e){return!!({"/events/eth-merge/":!0,"/events/btcamsterdam22/":!0,"/events/consensus-2023/":!0,"/events/killerwhales/":!0,"/events/bitcoin2023/":!0,"/link/":!0,"/app/prompt/":!0})[e]}function o(){let e=window.navigator.userAgent;return!!e.match("CMCApp")}function c(e){let t=window.navigator.userAgent,n=/iPad|iPhone|iPod/.test(t)&&!window.MSStream,r=t.includes("Safari")&&!t.includes("Chrome")&&!t.includes("CriOS");return n&&r}function s(){return"true"===localStorage.getItem("cmc_flag_in_app")}try{let l=e=>{let l=new URL(e||location.href),u=t(l.pathname),p=r()||a(l.search)||i(u)||o()||c(u)||s();if(n&&console.log("shouldHideBanner",p),p){let m=document.createElement("style");m.setAttribute("id","app-banner-style"),document.head.appendChild(m),m.sheet.insertRule(".app-banner-new { display: none !important; }",0)}else{let d=document.querySelector("#app-banner-style");d&&d.remove()}};l(),window.navigation&&window.navigation.addEventListener("navigate",e=>{l(e.destination.url)})}catch(u){console.log("shouldHide",u)}};__cookieBannerInitialScriptsDemoCode();</script><script type="speculationrules">{"prefetch":[{"source":"document","where":{"and":[{"href_matches":"/*","relative_to":"document"}]},"eagerness":"moderate"}]}</script><style data-hide-bottom-popup="true">\n              .cmc-bottom-popup {\n                bottom: -1000px!important;\n              }\n            </style><style data-hide-onetrust="true">\n              #onetrust-banner-sdk {\n                bottom: -1000px!important;\n              }\n            </style><script data-nscript="beforeInteractive" crossorigin="anonymous">\n            (function() {\n              if (false) return;\n              window.__renderTime__ = {"pageRender":1772712185159};\n              window.__renderTime__.pageLoad = Date.now();\n            })();\n            (function() {if (!!window.__RESOURCE_ERROR__) return;window.__RESOURCE_ERROR__ = [];var collectError = function(item) { window.__RESOURCE_ERROR__.push(item) };window.addEventListener(\'error\', function (e) {var sourceUrl = e.target && (e.target.src || e.target.href);sourceUrl && collectError({ type: e.type || \'error\', url: sourceUrl, status: -1, msg: e.message });}, true);var _oldFetch = window.fetch;var _oldOpen = XMLHttpRequest.prototype.open;var _oldSend = XMLHttpRequest.prototype.send;window.fetch = function() {var __url__ = String(arguments[0] && (arguments[0].url || arguments[0]));return _oldFetch.apply(this, arguments).then(res => {res.status >= 400 && collectError({ type: \'fetch\', url: __url__, status: res.status || -1, msg: res.statusText });return res;}).catch(function(e) {collectError({ type: \'fetch\', url: __url__, status: -1, msg: e.message });throw e;});};XMLHttpRequest.prototype.open = function () {this.__url__ = String(arguments[1]);return _oldOpen.apply(this, arguments);};XMLHttpRequest.prototype.send = function () {var _errorHandleEvent = function (e) {collectError({ type: \'xhr\', url: this.__url__, status: this.status, msg: this.statusText });};var _loadHandleEvent = function (e) {this.status >= 400 && collectError({ type: \'xhr\', url: this.__url__, status: this.status, msg: this.statusText });};this.addEventListener(\'error\', _errorHandleEvent);this.addEventListener(\'load\', _loadHandleEvent);return _oldSend.apply(this, arguments);};\n})();\n            window.cachedWidth = window.innerWidth;\n         </script><link rel="preload" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/a3554a6a5000146b.css" as="style" crossorigin="anonymous"/><link rel="stylesheet" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/a3554a6a5000146b.css" crossorigin="anonymous" data-n-g=""/><link rel="preload" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/796750977a958370.css" as="style" crossorigin="anonymous"/><link rel="stylesheet" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/796750977a958370.css" crossorigin="anonymous" data-n-p=""/><link rel="preload" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/f4c0ce5f7aa8cad1.css" as="style" crossorigin="anonymous"/><link rel="stylesheet" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/f4c0ce5f7aa8cad1.css" crossorigin="anonymous" data-n-p=""/><link rel="preload" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/4f561b54ad7fa9f6.css" as="style" crossorigin="anonymous"/><link rel="stylesheet" href="https://s2.coinmarketcap.com/v1/cmc/_next/static/css/4f561b54ad7fa9f6.css" crossorigin="anonymous"/><noscript data-n-css=""></noscript><script defer="" crossorigin="anonymous" nomodule="" src="https://s2.coinmarketcap.com/v1/cmc/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><script defer="" src="https://s2.coinmarketcap.com/v1/cmc/_next/static/chunks/78720.dece70035822f77b.js" crossorigin="anonymous"></script><script src="https://s2.coinmarketcap.com/v1/cmc/_next/static/chunks/webpac

In [67]:
soup = BeautifulSoup(page.text)

In [69]:
soup

<!DOCTYPE html>
<html dir="ltr" lang="en"><head><meta charset="utf-8"/><meta content="ie=edge" http-equiv="x-ua-compatible"/><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" name="viewport"/><meta content="https://coinmarketcap.com/" property="og:url"/><link href="https://coinmarketcap.com/" rel="canonical"/><link href="https://coinmarketcap.com/ar/" hreflang="ar" rel="alternate"/><link href="https://coinmarketcap.com/bg/" hreflang="bg" rel="alternate"/><link href="https://coinmarketcap.com/cs/" hreflang="cs" rel="alternate"/><link href="https://coinmarketcap.com/da/" hreflang="da" rel="alternate"/><link href="https://coinmarketcap.com/de/" hreflang="de" rel="alternate"/><link href="https://coinmarketcap.com/el/" hreflang="el" rel="alternate"/><link href="https://coinmarketcap.com/" hreflang="en" rel="alternate"/><link href="https://coinmarketcap.com/es/" hreflang="es" rel="alternate"/><link href="https://coinmarketcap.com/fi/" hreflang="fi" rel="alternate"/><link href="https://coinmarketcap.com/fr/" hreflang="fr" rel="alternate"/><link href="https://coinmarketcap.com/hi/" hreflang="hi" rel="alternate"/><link href="https://coinmarketcap.com/hu/" hreflang="hu" rel="alternate"/><link href="https://coinmarketcap.com/id/" hreflang="id" rel="alternate"/><link href="https://coinmarketcap.com/it/" hreflang="it" rel="alternate"/><link href="https://coinmarketcap.com/ja/" hreflang="ja" rel="alternate"/><link href="https://coinmarketcap.com/ko/" hreflang="ko" rel="alternate"/><link href="https://coinmarketcap.com/nl/" hreflang="nl" rel="alternate"/><link href="https://coinmarketcap.com/no/" hreflang="no" rel="alternate"/><link href="https://coinmarketcap.com/pl/" hreflang="pl" rel="alternate"/><link href="https://coinmarketcap.com/pt-br/" hreflang="pt-br" rel="alternate"/><link href="https://coinmarketcap.com/ro/" hreflang="ro" rel="alternate"/><link href="https://coinmarketcap.com/ru/" hreflang="ru" rel="alternate"/><link href="https://coinmarketcap.com/sk/" hreflang="sk" rel="alternate"/><link href="https://coinmarketcap.com/sv/" hreflang="sv" rel="alternate"/><link href="https://coinmarketcap.com/th/" hreflang="th" rel="alternate"/><link href="https://coinmarketcap.com/tr/" hreflang="tr" rel="alternate"/><link href="https://coinmarketcap.com/uk/" hreflang="uk" rel="alternate"/><link href="https://coinmarketcap.com/ur/" hreflang="ur" rel="alternate"/><link href="https://coinmarketcap.com/vi/" hreflang="vi" rel="alternate"/><link href="https://coinmarketcap.com/zh-tw/" hreflang="zh-tw" rel="alternate"/><link href="https://coinmarketcap.com/zh/" hreflang="zh" rel="alternate"/><link href="/manifest.json" rel="manifest"/><title>Cryptocurrency Prices, Charts And Market Capitalizations | CoinMarketCap</title><meta content="Cryptocurrency Prices, Charts And Market Capitalizations | CoinMarketCap" property="og:title"/><meta content="Top cryptocurrency prices and charts, listed by market capitalization. Free access to current and historic data for Bitcoin and thousands of altcoins." name="description"/><meta content="Top cryptocurrency prices and charts, listed by market capitalization. Free access to current and historic data for Bitcoin and thousands of altcoins." property="og:description"/><script type="application/ld+json">{"@context":"http://schema.org","@type":"Organization","name":"CoinMarketCap","url":"https://coinmarketcap.com","logo":"https://coinmarketcap.com/apple-touch-icon.png","sameAs":["https://www.facebook.com/CoinMarketCap/","https://twitter.com/coinmarketcap"]}</script><script type="application/ld+json">{"@context":"http://schema.org","@type":"Table","about":"Cryptocurrency Prices Today"}</script><meta content="43" name="next-head-count"/><script>if(top!==self){location.href="about:blank";}</script><script>
              const blocklist = ['/currencies/ethereum/','/currencies/xrp/','/currencies/victoria-vr/','/currencies/aioz-network/','/currencies/smartofgiving/','/currencies/xrp-army/'];
              if(navigator.userAgent.includes("Googlebot") && blocklist.some(path => location.pathname.includes(path))) {
                const meta = document.createElement("meta");
                meta.setAttribute("http-equiv", "Content-Security-Policy");
                meta.setAttribute("content", "default-src 'none'; base-uri 'none'");
                document.head.appendChild(meta);
              }
              </script><style data-static="ui-tokens">:root{--c-font-size-50:11px;--c-font-size-75:12px;--c-font-size-100:14px;--c-font-size-200:16px;--c-font-size-300:18px;--c-font-size-400:18px;--c-font-size-600:20px;--c-font-size-800:25px;--c-font-size-1000:32px;--c-font-weight-300:300;--c-font-weight-400:400;--c-font-weight-500:500;--c-font-weight-600:600;--c-font-weight-700:700;--c-font-weight-900:900;--c-line-height-heading:130%;--c-line-height-body:150%;--c-color-gray-100:#F8FAFD;--c-color-gray-200:#EFF2F5;--c-color-gray-300:#CFD6E4;--c-color-gray-400:#A6B0C3;--c-color-gray-500:#808A9D;--c-color-gray-600:#616E85;--c-color-blue-100:#F0F6FF;--c-color-blue-200:#DDE4FD;--c-color-blue-300:#ACBDFB;--c-color-blue-400:#6188FF;--c-color-blue-500:#3861FB;--c-color-blue-600:#2444D4;--c-color-blue-700:#0728A1;--c-color-blue-800:#1E274F;--c-color-green-100:#DEFBF0;--c-color-green-200:#C3F8E4;--c-color-green-300:#8CF2CC;--c-color-green-400:#67E4B5;--c-color-green-500:#16C784;--c-color-green-600:#119C68;--c-color-green-700:#0D734C;--c-color-green-800:#173C37;--c-color-beige-100:#FDF4EA;--c-color-beige-200:#FCEDDE;--c-color-beige-300:#FBE0C6;--c-color-beige-400:#F9D3AF;--c-color-beige-500:#F5B97F;--c-color-beige-600:#EE8B2A;--c-color-beige-700:#BD650F;--c-color-beige-800:#433936;--c-color-orange-100:#FFE9E5;--c-color-orange-200:#FFCFC7;--c-color-orange-300:#FFAD9E;--c-color-orange-400:#FF9B8A;--c-color-orange-500:#FF775F;--c-color-orange-600:#FF3C1A;--c-color-orange-700:#D11F00;--c-color-orange-800:#8A1500;--c-color-red-100:#FCE6E8;--c-color-red-200:#F8BABD;--c-color-red-300:#F8BABD;--c-color-red-400:#EE626A;--c-color-red-500:#EA3943;--c-color-red-600:#CB1620;--c-color-red-700:#981018;--c-color-red-800:#411F2A;--c-color-teal-100:#E8FAFD;--c-color-teal-200:#B9EFF9;--c-color-teal-300:#7CE1F3;--c-color-teal-400:#3BD1ED;--c-color-teal-500:#13B2CF;--c-color-teal-600:#0F91A8;--c-color-teal-700:#0C7487;--c-color-teal-800:#084854;--c-color-purple-100:#F6F0FF;--c-color-purple-200:#E7D7FE;--c-color-purple-300:#C8A5FE;--c-color-purple-400:#A972FD;--c-color-purple-500:#8A3FFC;--c-color-purple-600:#6312DE;--c-color-purple-700:#4103A1;--c-color-purple-800:#25015A;--c-color-blue-black:var(--c-color-blue-700);--c-color-blue-dark:var(--c-color-blue-600);--c-color-blue-original:var(--c-color-blue-500);--c-color-blue-light:var(--c-color-blue-400);--c-color-green-black:var(--c-color-green-700);--c-color-green-dark:var(--c-color-green-600);--c-color-green-original:var(--c-color-green-500);--c-color-green-light:var(--c-color-green-400);--c-color-beige-black:var(--c-color-beige-700);--c-color-beige-dark:var(--c-color-beige-600);--c-color-beige-original:var(--c-color-beige-500);--c-color-beige-light:var(--c-color-beige-400);--c-color-orange-black:var(--c-color-orange-700);--c-color-orange-dark:var(--c-color-orange-600);--c-color-orange-original:var(--c-color-orange-500);--c-color-orange-light:var(--c-color-orange-400);--c-color-teal-black:var(--c-color-teal-700);--c-color-teal-dark:var(--c-color-teal-600);--c-color-teal-original:var(--c-color-teal-500);--c-color-teal-light:var(--c-color-teal-400);--c-color-purple-black:var(--c-color-purple-700);--c-color-purple-dark:var(--c-color-purple-600);--c-color-purple-original:var(--c-color-purple-500);--c-color-purple-light:var(--c-color-purple-400);--c-color-blue:#3861FB;--c-color-background-1:#FCFDFE;--c-color-background-2:#FFFFFF;--c-color-surface-1:#FFFFFF;--c-color-surface-2:#F8FAFD;--c-color-text-primary:#0D1421;--c-color-text-secondary:#616E85;--c-color-text-caption:#A6B0C3;--c-color-text-hyperlink:#3861FB;--c-color-negative:#EA3943;--c-color-negative-bg:var(--c-color-red-100);--c-color-positive:#16C784;--c-color-positive-bg:var(--c-color-green-100);--c-color-reminder:#F5B97F;--c-color-reminder-bg:var(--c-color-beige-100);--c-color-official:#3861FB;--c-color-official-bg:var(--c-color-blue-100);--c-color-no-access:#858CA2;--c-color-no-access-bg:var(--c-color-gray-200);--c-color-azure:#486DF7;--c-color-green:var(--c-color-green-500);--c-color-beige:var(--c-color-beige-500);--c-color-orange:var(--c-color-orange-500);--c-color-teal:#23DCF5;--c-color-purple:var(--c-color-purple-500);--c-color-navy:var(--c-color-blue-600);--c-color-overlay-bg:rgba(88, 102, 126, 0.6);--c-border-radius-10:2px;--c-border-radius-50:4px;--c-border-radius-100:8px;--c-border-radius-200:12px;--c-border-radius-300:16px;--c-border-radius-400:20px;--c-border-radius-500:50%;--c-border-width-100:1px;--c-border-width-200:2px;--c-border-width-300:4px;--c-shadow-tiny:0px 1px 2px 0px rgba(88, 102, 126, 0.12), 0px 4px 24px 0px rgba(88, 102, 126, 0.08);--c-shadow-overlay:0px 8px 32px 0px rgba(128, 138, 157, 0.24), 0px 1px 2px 0px rgba(128, 138, 157, 0.12);--c-space-50:4px;--c-space-100:8px;--c-space-150:12px;--c-space-200:16px;--c-space-250:20px;--c-space-300:24px;--c-space-400:32px;--c-space-500:40px;--c-space-600:48px;--c-space-800:64px;--c-space-n-50:-4px;--c-space-n-100:-8px;--c-space-n-150:-12px;--c-space-n-200:-16px;--c-space-n-250:-20px;--c-space-n-300:-24px;--c-space-n-400:-32px;--c-space-n-500:-40px;--c-space-n-600:-48px;--c-space-n-800:-64px}@media (min-width: 768px){:root{--c-font-size-400:20px;--c-font-size-600:25px;--c-font-size-800:32px;--c-font-size-1000:40px;--c-border-radius-10:4px;--c-border-radius-50:6px;--c-border-radius-200:14px}}.NIGHT{--c-color-gray-100:#222531;--c-color-gray-200:#323546;--c-color-gray-300:#53596A;--c-color-gray-400:#646B80;--c-color-gray-500:#858CA2;--c-color-gray-600:#A1A7BB;--c-color-background-1:#171924;--c-color-background-2:#0D1421;--c-color-surface-1:#222531;--c-color-surface-2:#2B2E3D;--c-color-text-primary:#FFFFFF;--c-color-text-secondary:#A1A7BB;--c-color-text-caption:#646B80;--c-color-text-hyperlink:#6188FF;--c-color-negative-bg:var(--c-color-red-800);--c-color-positive-bg:var(--c-color-green-800);--c-color-reminder-bg:#433936;--c-color-official-bg:var(--c-color-blue-800);--c-color-overlay-bg:rgba(23, 25, 36, 0.6);--c-shadow-tiny:0px 1px 2px 0px rgba(13, 20, 33, 0.24), 0px 4px 24px 0px rgba(13, 20, 33, 0.12);;--c-shadow-overlay:0px 8px 32px 0px #0D1421, 0px 1px 2px 0px #0D1421}</style><link as="font" crossorigin="anonymous" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Regular-new.woff2" rel="preload" type="font/woff2"/><link href="https://s2.coinmarketcap.com/static/cloud/styles/ui_v072v1.css" rel="stylesheet"/><link as="font" crossorigin="anonymous" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Medium-new.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="anonymous" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-SemiBold-new.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="anonymous" href="https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Bold-new.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="anonymous" href="https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.woff" rel="preload" type="font/woff"/><style>@font-face{font-family:'Inter';font-style:normal;font-weight:400;src:url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Regular-new.woff2') format('woff2'),url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Regular-new.woff') format('woff');font-display:swap;}@font-face{font-family:'Inter';font-style:normal;font-weight:500;src:url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Medium-new.woff2') format('woff2'),url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Medium-new.woff') format('woff');font-display:swap;}@font-face{font-family:'Inter';font-style:normal;font-weight:600;src:url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-SemiBold-new.woff2') format('woff2'),url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-SemiBold-new.woff') format('woff');font-display:swap;}@font-face{font-family:'Inter';font-style:normal;font-weight:700;src:url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Bold-new.woff2') format('woff2'),url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Bold-new.woff') format('woff');font-display:swap;}@font-face{font-family:'Inter';font-style:normal;font-weight:900;src:url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Black-new.woff2') format('woff2'),url('https://s2.coinmarketcap.com/static/cloud/fonts/inter/Inter-Black-new.woff') format('woff');font-display:swap;}@font-face{font-family:'CMC V2';src:url('https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.woff') format('woff'),url('https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.ttf') format('truetype'),url('https://s2.coinmarketcap.com/static/cloud/fonts/cmc-v2/CMC-V2.svg#CMC-V2') format('svg');font-weight:normal;font-style:normal;font-display:swap;}*,*:before,*:after{box-sizing:border-box;border-spacing:0;font-family:Inter,-apple-system,BlinkMacSystemFont,'segoe ui',Roboto,Helvetica,Arial,sans-serif;}</style><link crossorigin="anonymous" href="https://s2.coinmarketcap.com" rel="preconnect"/><link crossorigin="anonymous" href="https://s3.coinmarketcap.com" rel="preconnect"/><meta content="image/png" property="og:image:type"/><meta content="600" property="og:image:width"/><meta content="315" property="og:image:height"/><meta content="CoinMarketCap" property="og:site_name"/><meta content="website" property="og:type"/><meta content="summary_large_image" name="twitter:card"/><link href="/apple-touch-icon.png" rel="apple-touch-icon"/><link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/><link as="script" href="https://cdn.fuseplatform.net/publift/tags/2/3570/fuse.js" rel="preload"/><meta content="https://s2.coinmarketcap.com/static/cloud/img/splash_600x315_1.png?_=790090e" property="og:image"/><meta content="EDc1reqlQ-zAgeRrrgAxRXNK-Zs9JgpE9a0wdaoSO9A" name="google-site-verification"/><script>const __cookieBannerInitialScriptsDemoCode=()=>{let e=["ar","bg","cs","da","de","el","en","es","fi","fr","hi","hu","id","it","ja","ko","nl","no","pl","pt-br","ro","ru","sk","sv","th","tr","uk","ur","vi","zh-tw","zh"];function t(t){let n=e.join("|"),r=RegExp(`^/(${n})/?`);return t.replace(r,"/")}let n=!("cn-test.coinmarketcap.com"===location.host||"coinmarketcap.com"===location.host);function r(){let e=new Date(JSON.parse(localStorage.getItem("appBannerAppear")||"{}").value||0).getTime();return new Date().getTime()-e<(n?6e4:864e6)}function a(e){let t=e,n=t.includes("utm_source=coinmarketcap")||t.includes("app=");if(n)try{localStorage.setItem("cmc_flag_in_app","true")}catch(r){}return n}function i(e){return!!({"/events/eth-merge/":!0,"/events/btcamsterdam22/":!0,"/events/consensus-2023/":!0,"/events/killerwhales/":!0,"/events/bitcoin2023/":!0,"/link/":!0,"/app/prompt/":!0})[e]}function o(){let e=window.navigator.userAgent;return!!e.match("CMCApp")}function c(e){let t=window.navigator.userAgent,n=/iPad|iPhone|iPod/.test(t)&&!window.MSStream,r=t.includes("Safari")&&!t.includes("Chrome")&&!t.includes("CriOS");return n&&r}function s(){return"true"===localStorage.getItem("cmc_flag_in_app")}try{let l=e=>{let l=new URL(e||location.href),u=t(l.pathname),p=r()||a(l.search)||i(u)||o()||c(u)||s();if(n&&console.log("shouldHideBanner",p),p){let m=document.createElement("style");m.setAttribute("id","app-banner-style"),document.head.appendChild(m),m.sheet.insertRule(".app-banner-new { display: none !important; }",0)}else{let d=document.querySelector("#app-banner-style");d&&d.remove()}};l(),window.navigation&&window.navigation.addEventListener("navigate",e=>{l(e.destination.url)})}catch(u){console.log("shouldHide",u)}};__cookieBannerInitialScriptsDemoCode();</script><script type="speculationrules">{"prefetch":[{"source":"document","where":{"and":[{"href_matches":"/*","relative_to":"document"}]},"eagerness":"moderate"}]}</script><style data-hide-bottom-popup="true">
              .cmc-bottom-popup {
                bottom: -1000px!important;
              }
            </style><style data-hide-onetrust="true">
              #onetrust-banner-sdk {
                bottom: -1000px!important;
              }
            </style><script crossorigin="anonymous" data-nscript="beforeInteractive">
            (function() {
              if (false) return;
              window.__renderTime__ = {"pageRender":1772709241687};
              window.__renderTime__.pageLoad = Date.now();
            })();
            (function() {if (!!window.__RESOURCE_ERROR__) return;window.__RESOURCE_ERROR__ = [];var collectError = function(item) { window.__RESOURCE_ERROR__.push(item) };window.addEventListener('error', function (e) {var sourceUrl = e.target && (e.target.src || e.target.href);sourceUrl && collectError({ type: e.type || 'error', url: sourceUrl, status: -1, msg: e.message });}, true);var _oldFetch = window.fetch;var _oldOpen = XMLHttpRequest.prototype.open;var _oldSend = XMLHttpRequest.prototype.send;window.fetch = function() {var __url__ = String(arguments[0] && (arguments[0].url || arguments[0]));return _oldFetch.apply(this, arguments).then(res => {res.status >= 400 && collectError({ type: 'fetch', url: __url__, status: res.status || -1, msg: res.statusText });return res;}).catch(function(e) {collectError({ type: 'fetch', url: __url__, status: -1, msg: e.message });throw e;});};XMLHttpRequest.prototype.open = function () {this.__url__ = String(arguments[1]);return _oldOpen.apply(this, arguments);};XMLHttpRequest.prototype.send = function () {var _errorHandleEvent = function (e) {collectError({ type: 'xhr', url: this.__url__, status: this.status, msg: this.statusText });};var _loadHandleEvent = function (e) {this.status >= 400 && collectError({ type: 'xhr', url: this.__url__, status: this.status, msg: this.statusText });};this.addEventListener('error', _errorHandleEvent);this.addEventListener('load', _loadHandleEvent);return _oldSend.apply(this, arguments);};
})();
            window.cachedWidth = window.innerWidth;

In [81]:
a = soup.find_all("p", class_="sc-c1554bc0-0 eWrlhi coin-item-name")
a

[<p class="sc-c1554bc0-0 eWrlhi coin-item-name">CoinMarketCap 20 Index DTF</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Bitcoin</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Ethereum</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Tether</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">BNB</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">XRP</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">USDC</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Solana</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">TRON</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Dogecoin</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Cardano</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Bitcoin Cash</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">UNUS SED LEO</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Hyperliquid</p>,
 <p class="sc-c1554bc0-0 eWrlhi coin-item-name">Monero</p>]

In [83]:
coin = []
for i in a:
    coin.append(i.text)

In [85]:
coin

['CoinMarketCap 20 Index DTF',
 'Bitcoin',
 'Ethereum',
 'Tether',
 'BNB',
 'XRP',
 'USDC',
 'Solana',
 'TRON',
 'Dogecoin',
 'Cardano',
 'Bitcoin Cash',
 'UNUS SED LEO',
 'Hyperliquid',
 'Monero']

In [ ]:
len(d)

In [87]:
b = soup.find_all("div", class_="sc-631098c-0 ilZTOW")

In [89]:
b

[<div class="sc-631098c-0 ilZTOW"><span>$149.34</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$73,112.98</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$2,148.64</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$1.00</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$662.44</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$1.44</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$0.9999</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$92.54</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$0.2847</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$0.09767</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$0.2763</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$466.41</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$8.98</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$31.98</span></div>,
 <div class="sc-631098c-0 ilZTOW"><span>$370.65</span></div>]

In [31]:
price = []
for i in b:
    price.append(i.text)

In [35]:
price

['$149.20',
 '$73,330.66',
 '$2,155.37',
 '$1.00',
 '$664.04',
 '$1.45',
 '$0.9999',
 '$92.74',
 '$0.2847',
 '$0.09773',
 '$0.2768',
 '$467.11',
 '$8.98',
 '$32.04',
 '$372.25']

In [51]:
c = soup.find_all("span", class_="sc-d5c03ba0-0 dJLZma")
c

[<span class="sc-d5c03ba0-0 dJLZma"><span class="icon-Caret-down" style="width:12px;height:18px;display:inline-block"></span>0.01%</span>,
 <span class="sc-d5c03ba0-0 dJLZma"><span class="icon-Caret-down" style="width:12px;height:18px;display:inline-block"></span>0.47%</span>,
 <span class="sc-d5c03ba0-0 dJLZma"><span class="icon-Caret-down" style="width:12px;height:18px;display:inline-block"></span>1.19%</span>,
 <span class="sc-d5c03ba0-0 dJLZma"><span class="icon-Caret-down" style="width:12px;height:18px;display:inline-block"></span>5.20%</span>,
 <span class="sc-d5c03ba0-0 dJLZma"><span class="icon-Caret-down" style="width:12px;height:18px;display:inline-block"></span>6.24%</span>,
 <span class="sc-d5c03ba0-0 dJLZma"><span class="icon-Caret-down" style="width:12px;height:18px;display:inline-block"></span>2.31%</span>,
 <span class="sc-d5c03ba0-0 dJLZma"><span class="icon-Caret-down" style="width:12px;height:18px;display:inline-block"></span>1.12%</span>]

In [43]:
hour_per = []
for i in c:
    hour_per.append(i.text)

In [47]:
hour_per

['0.01%', '0.47%', '1.19%', '5.20%', '6.24%', '2.31%', '1.12%']

In [156]:
d = soup.find_all("span", class_="sc-d5c03ba0-0 dJLZma")
d[0].text

'0.49%'

In [158]:
day_per = []
for i in d:
    day_per.append(i.text)

In [160]:
len(day_per)

19

In [174]:
e = soup.find_all("span", class_="sc-d5c03ba0-0 ivIsIp")
e[0].text

'2.12%'

In [176]:
week_per = []
for i in e:
    week_per.append(i.text)

In [178]:
len(week_per)

26

In [119]:
d = {"hour_per":hour_per,
  "day_per":day_per}

In [121]:
df1 = pd.DataFrame(d)

In [123]:
df1

   hour_per day_per
0     0.49%   0.49%
1     0.19%   0.19%
2     0.26%   0.26%
3     0.00%   0.00%
4     0.51%   0.51%
5     0.02%   0.02%
6     0.02%   0.02%
7     0.48%   0.48%
8     0.19%   0.19%
9     0.21%   0.21%
10    0.85%   0.85%
11    0.73%   0.73%
12    1.14%   1.14%
13    1.14%   1.14%
14    8.55%   8.55%
15    1.35%   1.35%
16    0.03%   0.03%
17    1.00%   1.00%
18    0.55%   0.55%

In [125]:
pd.concat([df, df1], axis=1)

                          coin       price hour_per day_per
0   CoinMarketCap 20 Index DTF     $139.34    0.49%   0.49%
1                      Bitcoin  $67,933.61    0.19%   0.19%
2                     Ethereum   $1,993.80    0.26%   0.26%
3                       Tether       $1.00    0.00%   0.00%
4                          BNB     $631.93    0.51%   0.51%
5                          XRP       $1.36    0.02%   0.02%
6                         USDC       $1.00    0.02%   0.02%
7                       Solana      $85.60    0.48%   0.48%
8                         TRON     $0.2821    0.19%   0.19%
9                     Dogecoin    $0.09150    0.21%   0.21%
10                     Cardano     $0.2694    0.85%   0.85%
11                Bitcoin Cash     $442.13    0.73%   0.73%
12                 Hyperliquid      $32.78    1.14%   1.14%
13                UNUS SED LEO       $9.04    1.14%   1.14%
14                   Chainlink       $8.79    8.55%   8.55%
15                         NaN         NaN    1.35%   1.35%
16                         NaN         NaN    0.03%   0.03%
17                         NaN         NaN    1.00%   1.00%
18                         NaN         NaN    0.55%   0.55%

In [101]:
coin_tags = soup.find_all("p", class_="sc-c1554bc0-0 eWrlhi coin-item-name")

coin_names = [tag.get_text(strip=True) for tag in coin_tags]

# only first 100
coin_names = coin_names[:100]

for index, name in enumerate(coin_names, start=1):
    print(f"{index}. {name}")

1. CoinMarketCap 20 Index DTF
2. Bitcoin
3. Ethereum
4. Tether
5. BNB
6. XRP
7. USDC
8. Solana
9. TRON
10. Dogecoin
11. Cardano
12. Bitcoin Cash
13. UNUS SED LEO
14. Hyperliquid
15. Monero

In [105]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Collecting certifi>=2026.1.4 (from selenium)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /opt/anaconda3/lib/python3.12/site-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /opt/anaconda3/lib/python3.12/site-packages (from selenium) (1.8.0)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: sortedcontainers in /opt/anaconda3/lib/python3.12/site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.12/site-packages (from trio<1.0,>=0.31.0->selenium) (3.7)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /opt/anaconda3/lib/python3.12/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Collecting h11<1,>=0.16.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 2.4 MB/s eta 0:00:00m eta 0:00:010:01:01
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.7/153.7 kB 2.4 MB/s eta 0:00:0031m3.0 MB/s eta 0:00:01
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 4.0 MB/s eta 0:00:00[36m0:00:01[36m0:00:01
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 1.8 MB/s eta 0:00:00MB/s eta 0:00:01
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.6/67.6 kB 1.8 MB/s eta 0:00:00 MB/s eta 0:00:01
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: urllib3, h11, certifi, attrs, wsproto, outcome, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.2
    Uninstalling urllib3-2.2.2:
      Successfully uninstalled urllib3-2.2.2
  Attempting uninstall: h11
    Found existing installation: h11 0.14.0
    Uninstalling h11-0.14.0:
      Successfully uninstalled h11-0.14.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2025.10.5
    Uninstalling certifi-2025.10.5:
      Successfully uninstalled certifi-2025.10.5
  Attempting uninstall: attrs
    Found existing installation: attrs 23.1.0
    Uninstalling attrs-23.1.0:
      Successfully uninstalled attrs-23.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aext-panels-server 4.0.15 requires anaconda-cloud-auth, which is not installed.
httpcore 1.0.2 requires h11<0.15,>=0.13, but you have h11 0.16.0 which is incompatible.
Successfully installed attrs-25.4.0 certifi-2026.2.25 h11-0.16.0 outcome-1.3.0.post0 selenium-4.41.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 wsproto-1.3.2

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time

# Optional: run in headless mode
chrome_options = Options()
#chrome_options.add_argument("--headless")
chrome_options.add_argument("--start-maximized")

driver = webdriver.Chrome(options=chrome_options)

url = "https://coinmarketcap.com/"
driver.get(url)

# wait for page to load fully
time.sleep(5)

# Find all coin name elements
coins = driver.find_elements(By.XPATH, "//p[contains(@class,'coin-item-name')]")

coin_names = []

for coin in coins[:100]:
    coin_names.append(coin.text)

# Print first 100
for i, name in enumerate(coin_names, start=1):
    print(i, name)

print("\nTotal Extracted:", len(coin_names))

driver.quit()

In [5]:
import requests

api_url = "https://api.coinmarketcap.com/data-api/v3/cryptocurrency/listing"

params = {
    "start": 1,
    "limit": 100,
    "sortBy": "market_cap",
    "sortType": "desc",
    "convert": "USD"
}

response = requests.get(api_url, params=params)
data = response.json()

coins = data["data"]["cryptoCurrencyList"]

names = [coin["name"] for coin in coins]

print("Total Names Extracted:", len(names))
print(names)

Total Names Extracted: 100
['Bitcoin', 'Ethereum', 'Tether USDt', 'BNB', 'XRP', 'USDC', 'Solana', 'TRON', 'Dogecoin', 'Cardano', 'Bitcoin Cash', 'UNUS SED LEO', 'Hyperliquid', 'Monero', 'Chainlink', 'Ethena USDe', 'Canton', 'Dai', 'Stellar', 'World Liberty Financial USD', 'Hedera', 'Litecoin', 'PayPal USD', 'Avalanche', 'Zcash', 'Sui', 'Toncoin', 'Shiba Inu', 'Cronos', 'Tether Gold', 'World Liberty Financial', 'Uniswap', 'PAX Gold', 'Polkadot', 'Mantle', 'Bittensor', 'Pi', 'Aster', 'Aave', 'MemeCore', 'Sky', 'Global Dollar', 'NEAR Protocol', 'OKB', 'Ripple USD', 'Bitget Token', 'Pepe', 'Internet Computer', 'Ethereum Classic', 'Ondo', 'Worldcoin', 'Polygon (prev. MATIC)', 'KuCoin Token', 'Midnight', 'USDD', 'Ethena', 'United Stables', 'Cosmos', 'Kaspa', 'GateToken', 'Quant', 'Flare', 'Algorand', 'Aptos', 'OFFICIAL TRUMP', 'Filecoin', 'Morpho', 'Pump.fun', 'Render', 'XDC Network', 'Jupiter', 'VeChain', 'Arbitrum', 'LayerZero', 'Stable', 'Nexo', 'Decred', 'Bonk', 'TrueUSD', 'Virtuals Protocol', 'Stacks', 'PancakeSwap', 'Pudgy Penguins', 'Sei', 'EURC', 'Kite', 'Dash', 'JUST', 'Tezos', 'ether.fi', 'Chiliz', 'Curve DAO Token', 'First Digital USD', 'Gnosis', 'pippin', 'Artificial Superintelligence Alliance', 'Humanity Protocol', 'Aerodrome Finance', 'Kaia', 'BitTorrent [New]']

In [7]:
import requests
import pandas as pd

# API endpoint used by CoinMarketCap website
api_url = "https://api.coinmarketcap.com/data-api/v3/cryptocurrency/listing"

params = {
    "start": 1,
    "limit": 100,          # Change this if you want more
    "sortBy": "market_cap",
    "sortType": "desc",
    "convert": "USD"
}

response = requests.get(api_url, params=params)
data = response.json()

coins = data["data"]["cryptoCurrencyList"]

# Extract required fields
coin_data = []
for coin in coins:
    coin_data.append({
        "Rank": coin["cmcRank"],
        "Name": coin["name"],
        "Symbol": coin["symbol"],
        "Price (USD)": coin["quotes"][0]["price"]
    })

# Convert to DataFrame
df = pd.DataFrame(coin_data)

# Save to CSV
#df.to_csv("coinmarketcap_top100.csv", index=False)

print("CSV file created successfully!")
print("Total Rows:", len(df))

CSV file created successfully!
Total Rows: 100

In [9]:
df

    Rank                                   Name Symbol   Price (USD)
0      1                                Bitcoin    BTC  7.286327e+04
1      2                               Ethereum    ETH  2.138363e+03
2      3                            Tether USDt   USDT  1.000080e+00
3      4                                    BNB    BNB  6.594578e+02
4      5                                    XRP    XRP  1.437010e+00
..   ...                                    ...    ...           ...
95    96  Artificial Superintelligence Alliance    FET  1.553822e-01
96    97                      Humanity Protocol      H  1.370377e-01
97    98                                   Kaia   KAIA  5.441807e-02
98    99                      Aerodrome Finance   AERO  3.677775e-01
99   100                       BitTorrent [New]    BTT  3.402341e-07

[100 rows x 4 columns]

In [14]:
import requests
import pandas as pd

api_url = "https://api.coinmarketcap.com/data-api/v3/cryptocurrency/listing"

params = {
    "start": 1,
    "limit": 1000,      # Change to 500 or 1000 if needed
    "sortBy": "market_cap",
    "sortType": "desc",
    "convert": "USD"
}

response = requests.get(api_url, params=params)
data = response.json()

coins = data["data"]["cryptoCurrencyList"]

coin_data = []

for coin in coins:
    quote = coin["quotes"][0]

    coin_data.append({
        "Rank": coin["cmcRank"],
        "Name": coin["name"],
        "Symbol": coin["symbol"],
        "Price (USD)": quote["price"],
        "1h %": quote["percentChange1h"],
        "24h %": quote["percentChange24h"],
        "7d %": quote["percentChange7d"],
        "Market Cap": quote["marketCap"],
        "Volume (24h)": quote["volume24h"]
    })

df = pd.DataFrame(coin_data)

df.to_csv("coinmarketcap_full_data.csv", index=False)

print("CSV file created successfully!")
print("Total Rows:", len(df))

CSV file created successfully!
Total Rows: 1000

In [2]:
df

,Rank,Name,Symbol,Price (USD),1h %,24h %,7d %,Market Cap,Volume (24h)
0,1,Bitcoin,BTC,67956.875631,0.241119,-1.510028,5.265265,1.359078e+12,2.807796e+10
1,2,Ethereum,ETH,1985.228815,0.495051,-0.535332,5.176109,2.396014e+11,1.279492e+10
2,3,Tether USDt,USDT,0.999907,-0.004038,-0.019082,-0.020970,1.839533e+11,5.585046e+10
3,4,BNB,BNB,627.402591,0.426044,-0.189094,4.372755,8.555164e+10,1.062458e+09
4,5,XRP,XRP,1.360978,0.114003,-0.277518,2.830854,8.332975e+10,1.518540e+09
...,...,...,...,...,...,...,...,...,...
995,996,XION,XION,0.114753,0.033574,0.192755,-7.169432,8.323857e+06,2.449695e+06
996,997,Harvest Finance,FARM,12.368137,1.141501,0.229302,10.249234,8.313657e+06,2.743915e+06
997,998,LUKSO,LYX,0.272015,-0.423592,0.536666,-7.778101,8.306238e+06,3.687572e+05
998,999,Aura,AURA,0.008570,-0.091961,-0.847439,9.897833,8.255036e+06,6.384839e+05
999,1000,Unicorn Fart Dust,UFD,0.008253,-0.468855,-0.810935,-2.377538,8.252826e+06,7.730246e+05

In [9]:
df["Market Cap"] = df["Market Cap"].apply(lambda x: f"{x:,.2f}")
df["Volume (24h)"] = df["Volume (24h)"].apply(lambda x: f"{x:,.2f}")

In [11]:
df

,Rank,Name,Symbol,Price (USD),1h %,24h %,7d %,Market Cap,Volume (24h)
0,1,Bitcoin,BTC,67956.88,0.24,-1.51,5.27,"1,359,078,050,356.43","28,077,957,224.44"
1,2,Ethereum,ETH,1985.23,0.50,-0.54,5.18,"239,601,359,264.81","12,794,918,183.67"
2,3,Tether USDt,USDT,1.00,-0.00,-0.02,-0.02,"183,953,266,032.46","55,850,456,091.76"
3,4,BNB,BNB,627.40,0.43,-0.19,4.37,"85,551,643,504.53","1,062,457,725.91"
4,5,XRP,XRP,1.36,0.11,-0.28,2.83,"83,329,746,045.97","1,518,539,862.88"
...,...,...,...,...,...,...,...,...,...
995,996,XION,XION,0.11,0.03,0.19,-7.17,"8,323,857.32","2,449,694.80"
996,997,Harvest Finance,FARM,12.37,1.14,0.23,10.25,"8,313,657.13","2,743,914.76"
997,998,LUKSO,LYX,0.27,-0.42,0.54,-7.78,"8,306,237.85","368,757.24"
998,999,Aura,AURA,0.01,-0.09,-0.85,9.90,"8,255,035.94","638,483.86"
999,1000,Unicorn Fart Dust,UFD,0.01,-0.47,-0.81,-2.38,"8,252,825.84","773,024.64"